library(argparse)
library(reshape2)
library(magrittr)
library(dplyr)
source("analysis/plotting_extras.R")
parser = ArgumentParser()
parser$add_argument("--input-csv", dest = "input_csv")
parser$add_argument("--output-tex", dest = "output_tex")
parser$add_argument("--rc", dest="rc", default="False")
args = parser$parse_args()

t = read.csv(args$input_csv)
out = t[,c(2,4,6,7)] %>% subset(reverse_complement == args$rc) %>% melt(id = c("k", "type", "reverse_complement")) %>% dcast(k ~ type)
cat(format_table(round(out, digits =2), c("$k$", "PyMF", "PyPMF"), "l | l l"), file = args$output_tex)
