library(argparse)
library(reshape2)
library(magrittr)
library(dplyr)
source("analysis/plotting_extras.R")
parser = ArgumentParser()
parser$add_argument("--input-csv", dest = "input_csv")
parser$add_argument("--output-tex", dest = "output_tex")
parser$add_argument("--rc", dest="rc", default="False")
parser$add_argument("--dale", dest="dale", default="False")
args = parser$parse_args()

t = read.csv(args$input_csv)
out = t %>% subset(reverse_complement == args$rc & dale_method == args$dale) %>%
    select("k", "hit_fraction")
cat(format_table(round(out, digits =2), c("$k$", "PyPMF"), "l | l"), file = args$output_tex)
